/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package menu;

/**
 *
 * @author Alamost7
 */
public class MenuCafe extends javax.swing.JFrame {

    /**
     * Creates new form MenuCafe
     */
    public MenuCafe() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">                          
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        cbxmieb = new javax.swing.JCheckBox();
        jLabel7 = new javax.swing.JLabel();
        txtqty1 = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        txtqty2 = new javax.swing.JTextField();
        cbxmiet = new javax.swing.JCheckBox();
        jLabel11 = new javax.swing.JLabel();
        txtqty3 = new javax.swing.JTextField();
        cbxmieu = new javax.swing.JCheckBox();
        txtqty4 = new javax.swing.JTextField();
        cbxmiec = new javax.swing.JCheckBox();
        jLabel12 = new javax.swing.JLabel();
        cbxmied = new javax.swing.JCheckBox();
        txtqty5 = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        cbxmiek = new javax.swing.JCheckBox();
        txtqty6 = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        cbxmies = new javax.swing.JCheckBox();
        txtqty7 = new javax.swing.JTextField();
        jLabel16 = new javax.swing.JLabel();
        cbxkopihtm = new javax.swing.JCheckBox();
        txtqty8 = new javax.swing.JTextField();
        jLabel17 = new javax.swing.JLabel();
        cbxkopis = new javax.swing.JCheckBox();
        txtqty9 = new javax.swing.JTextField();
        jLabel18 = new javax.swing.JLabel();
        cbxkopisd = new javax.swing.JCheckBox();
        txtqty10 = new javax.swing.JTextField();
        jLabel19 = new javax.swing.JLabel();
        cbxkopisu = new javax.swing.JCheckBox();
        txtqty11 = new javax.swing.JTextField();
        txtqty12 = new javax.swing.JTextField();
        jLabel20 = new javax.swing.JLabel();
        cbxkopisudi = new javax.swing.JCheckBox();
        txtqty13 = new javax.swing.JTextField();
        jLabel21 = new javax.swing.JLabel();
        cbxkopikotel = new javax.swing.JCheckBox();
        jLabel8 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        txttotal = new javax.swing.JTextArea();
        btnpesan = new javax.swing.JButton();
        btnreset = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Makanan:");

        jLabel2.setText("Minuman:");

        jLabel3.setText("Harga:");

        jLabel4.setText("Qty:");

        jLabel5.setText("Harga:");

        jLabel6.setText("Qty.");

        cbxmieb.setText("Mie Biasa");
        cbxmieb.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbxmiebActionPerformed(evt);
            }
        });

        jLabel7.setText("Rp.13.000");

        txtqty1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtqty1ActionPerformed(evt);
            }
        });

        jLabel10.setText("Rp.15.000");

        txtqty2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtqty2ActionPerformed(evt);
            }
        });

        cbxmiet.setText("Mie Telur");
        cbxmiet.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbxmietActionPerformed(evt);
            }
        });

        jLabel11.setText("Rp.23.000");

        txtqty3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtqty3ActionPerformed(evt);
            }
        });

        cbxmieu.setText("Mie Udang");
        cbxmieu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbxmieuActionPerformed(evt);
            }
        });

        txtqty4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtqty4ActionPerformed(evt);
            }
        });

        cbxmiec.setText("Mie Cumi");
        cbxmiec.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbxmiecActionPerformed(evt);
            }
        });

        jLabel12.setText("Rp.25.000");

        cbxmied.setText("Mie Daging");
        cbxmied.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbxmiedActionPerformed(evt);
            }
        });

        txtqty5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtqty5ActionPerformed(evt);
            }
        });

        jLabel13.setText("Rp.23.000");

        cbxmiek.setText("Mie Kepiting");
        cbxmiek.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbxmiekActionPerformed(evt);
            }
        });

        txtqty6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtqty6ActionPerformed(evt);
            }
        });

        jLabel14.setText("Rp.27.000");

        jLabel15.setText("Rp.30.000");

        cbxmies.setText("Mie Spesial");
        cbxmies.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbxmiesActionPerformed(evt);
            }
        });

        txtqty7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtqty7ActionPerformed(evt);
            }
        });

        jLabel16.setText("Rp.6.000");

        cbxkopihtm.setText("Kopi Hitam Saring");
        cbxkopihtm.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbxkopihtmActionPerformed(evt);
            }
        });

        txtqty8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtqty8ActionPerformed(evt);
            }
        });

        jLabel17.setText("Rp.10.000");

        cbxkopis.setText("Kopi Sangger");
        cbxkopis.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbxkopisActionPerformed(evt);
            }
        });

        txtqty9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtqty9ActionPerformed(evt);
            }
        });

        jLabel18.setText("Rp.12.000");

        cbxkopisd.setText("Kopi Sangger Dingin");
        cbxkopisd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbxkopisdActionPerformed(evt);
            }
        });

        txtqty10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtqty10ActionPerformed(evt);
            }
        });

        jLabel19.setText("Rp.12.000");

        cbxkopisu.setText("Kopi Susu");
        cbxkopisu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbxkopisuActionPerformed(evt);
            }
        });

        txtqty11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtqty11ActionPerformed(evt);
            }
        });

        txtqty12.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtqty12ActionPerformed(evt);
            }
        });

        jLabel20.setText("Rp.14.000");

        cbxkopisudi.setText("Kopi Susu Dingin");
        cbxkopisudi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbxkopisudiActionPerformed(evt);
            }
        });

        txtqty13.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtqty13ActionPerformed(evt);
            }
        });

        jLabel21.setText("Rp.14.000");

        cbxkopikotel.setText("Kopi Kocok Telur");
        cbxkopikotel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbxkopikotelActionPerformed(evt);
            }
        });

        jLabel8.setText("Menu yang dipesan :");

        txttotal.setColumns(20);
        txttotal.setRows(5);
        jScrollPane1.setViewportView(txttotal);

        btnpesan.setText("Pesan");
        btnpesan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnpesanActionPerformed(evt);
            }
        });

        btnreset.setText("Ulang");
        btnreset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnresetActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(cbxmieb, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(30, 30, 30))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(24, 24, 24)
                                .addComponent(jLabel1))
                            .addComponent(cbxmiet)
                            .addComponent(cbxmieu)
                            .addComponent(cbxmiec)
                            .addComponent(cbxmied))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(cbxmies, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cbxmiek))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel7, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel10, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel11, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel12, javax.swing.GroupLayout.Alignment.TRAILING))
                        .addGap(39, 39, 39))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(7, 7, 7)
                                .addComponent(jLabel3))
                            .addComponent(jLabel14)
                            .addComponent(jLabel15)
                            .addComponent(jLabel13))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(13, 13, 13)
                        .addComponent(jLabel4))
                    .addComponent(txtqty3, javax.swing.GroupLayout.DEFAULT_SIZE, 58, Short.MAX_VALUE)
                    .addComponent(txtqty4)
                    .addComponent(txtqty5)
                    .addComponent(txtqty6)
                    .addComponent(txtqty7)
                    .addComponent(txtqty2)
                    .addComponent(txtqty1, javax.swing.GroupLayout.Alignment.TRAILING))
                .addGap(91, 91, 91)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(cbxkopihtm)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addGap(22, 22, 22))
                    .addComponent(cbxkopis)
                    .addComponent(cbxkopisd)
                    .addComponent(cbxkopisu)
                    .addComponent(cbxkopisudi)
                    .addComponent(cbxkopikotel))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(43, 43, 43)
                        .addComponent(jLabel5))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(35, 35, 35)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel16, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel17)
                            .addComponent(jLabel18)
                            .addComponent(jLabel19)
                            .addComponent(jLabel20)
                            .addComponent(jLabel21))))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(63, 63, 63)
                        .addComponent(jLabel6))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(51, 51, 51)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtqty8, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtqty9, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtqty10, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtqty11, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtqty12, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtqty13, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(btnpesan)
                        .addGap(38, 38, 38)
                        .addComponent(btnreset))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(83, 83, 83)
                        .addComponent(jLabel8)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 459, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(147, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(49, 49, 49)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3)
                            .addComponent(jLabel4))
                        .addGap(83, 83, 83)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtqty3, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cbxmieu))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cbxmiec, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtqty4, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel5)
                            .addComponent(jLabel6))
                        .addGap(1, 1, 1)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(txtqty1, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(cbxkopihtm)
                                        .addComponent(jLabel16)
                                        .addComponent(txtqty8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                            .addComponent(cbxkopis)
                                            .addComponent(jLabel17)
                                            .addComponent(txtqty9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                            .addComponent(cbxkopisd)
                                            .addComponent(jLabel18)
                                            .addComponent(txtqty10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                            .addComponent(cbxkopisu)
                                            .addComponent(jLabel19)
                                            .addComponent(txtqty11, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addComponent(txtqty2, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(75, 75, 75))))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(1, 1, 1)
                                        .addComponent(jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                    .addComponent(cbxmieb, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addComponent(jLabel10)
                                        .addGap(70, 70, 70))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addComponent(cbxmiet)
                                        .addGap(72, 72, 72)))))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(cbxkopisudi)
                                    .addComponent(jLabel20)
                                    .addComponent(txtqty12, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(cbxkopikotel)
                                    .addComponent(jLabel21)
                                    .addComponent(txtqty13, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(1, 1, 1)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(txtqty5, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                            .addComponent(txtqty6, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(cbxmiek)))
                                    .addComponent(cbxmied))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(txtqty7, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(cbxmies, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 50, Short.MAX_VALUE)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel8)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 184, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnpesan)
                            .addComponent(btnreset))
                        .addGap(102, 102, 102))))
        );

        layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {cbxkopihtm, cbxkopikotel, cbxkopis, cbxkopisd, cbxkopisu, cbxkopisudi, cbxmiec, cbxmied, cbxmiek, cbxmies, cbxmiet, cbxmieu, jLabel10, jLabel11, jLabel12, jLabel13, jLabel14, jLabel15, jLabel16, jLabel17, jLabel18, jLabel19, jLabel20, jLabel21, txtqty1, txtqty10, txtqty11, txtqty12, txtqty13, txtqty2, txtqty3, txtqty4, txtqty5, txtqty6, txtqty7, txtqty8, txtqty9});

        pack();
    }// </editor-fold>                        

    private void cbxmiebActionPerformed(java.awt.event.ActionEvent evt) {                                        
        // TODO add your handling code here:
    }                                       

    private void txtqty1ActionPerformed(java.awt.event.ActionEvent evt) {                                        
        // TODO add your handling code here:
    }                                       

    private void txtqty2ActionPerformed(java.awt.event.ActionEvent evt) {                                        
        // TODO add your handling code here:
    }                                       

    private void cbxmietActionPerformed(java.awt.event.ActionEvent evt) {                                        
        // TODO add your handling code here:
    }                                       

    private void txtqty3ActionPerformed(java.awt.event.ActionEvent evt) {                                        
        // TODO add your handling code here:
    }                                       

    private void cbxmieuActionPerformed(java.awt.event.ActionEvent evt) {                                        
        // TODO add your handling code here:
    }                                       

    private void cbxmiecActionPerformed(java.awt.event.ActionEvent evt) {                                        
        // TODO add your handling code here:
    }                                       

    private void cbxmiedActionPerformed(java.awt.event.ActionEvent evt) {                                        
        // TODO add your handling code here:
    }                                       

    private void txtqty5ActionPerformed(java.awt.event.ActionEvent evt) {                                        
        // TODO add your handling code here:
    }                                       

    private void cbxmiekActionPerformed(java.awt.event.ActionEvent evt) {                                        
        // TODO add your handling code here:
    }                                       

    private void txtqty6ActionPerformed(java.awt.event.ActionEvent evt) {                                        
        // TODO add your handling code here:
    }                                       

    private void cbxmiesActionPerformed(java.awt.event.ActionEvent evt) {                                        
        // TODO add your handling code here:
    }                                       

    private void txtqty7ActionPerformed(java.awt.event.ActionEvent evt) {                                        
        // TODO add your handling code here:
    }                                       

    private void cbxkopihtmActionPerformed(java.awt.event.ActionEvent evt) {                                           
        // TODO add your handling code here:
    }                                          

    private void txtqty8ActionPerformed(java.awt.event.ActionEvent evt) {                                        
        // TODO add your handling code here:
    }                                       

    private void cbxkopisActionPerformed(java.awt.event.ActionEvent evt) {                                         
        // TODO add your handling code here:
    }                                        

    private void txtqty9ActionPerformed(java.awt.event.ActionEvent evt) {                                        
        // TODO add your handling code here:
    }                                       

    private void cbxkopisdActionPerformed(java.awt.event.ActionEvent evt) {                                          
        // TODO add your handling code here:
    }                                         

    private void txtqty10ActionPerformed(java.awt.event.ActionEvent evt) {                                         
        // TODO add your handling code here:
    }                                        

    private void cbxkopisuActionPerformed(java.awt.event.ActionEvent evt) {                                          
        // TODO add your handling code here:
    }                                         

    private void txtqty11ActionPerformed(java.awt.event.ActionEvent evt) {                                         
        // TODO add your handling code here:
    }                                        

    private void txtqty12ActionPerformed(java.awt.event.ActionEvent evt) {                                         
        // TODO add your handling code here:
    }                                        

    private void cbxkopisudiActionPerformed(java.awt.event.ActionEvent evt) {                                            
        // TODO add your handling code here:
    }                                           

    private void txtqty13ActionPerformed(java.awt.event.ActionEvent evt) {                                         
        // TODO add your handling code here:
    }                                        

    private void cbxkopikotelActionPerformed(java.awt.event.ActionEvent evt) {                                             
        // TODO add your handling code here:
    }                                            

    private void btnpesanActionPerformed(java.awt.event.ActionEvent evt) {                                         
        // TODO add your handling code here:
        String tampil;
        tampil = "";
        int bayar = 0;
        
        if(cbxmieb.isSelected()){
            int jumlah = Integer.parseInt(txtqty1.getText());
            int total;
            total=jumlah*13000;
            bayar=bayar+total;
            tampil +=cbxmieb.getText()+" Rp.13000"+ " x " +jumlah+ " = " + total+"\n";
        }
        if(cbxmiet.isSelected()){
            int jumlah = Integer.parseInt(txtqty2.getText());
            int total;
            total=jumlah*15000;
            bayar=bayar+total;
            tampil +=cbxmiet.getText()+" Rp.15000"+ " x " +jumlah+ " = " + total+"\n";
        }
        if(cbxmieu.isSelected()){
            int jumlah = Integer.parseInt(txtqty3.getText());
            int total;
            total=jumlah*23000;
            bayar=bayar+total;
            tampil +=cbxmieu.getText()+" Rp.23000"+ " x " +jumlah+ " = " + total+"\n";
        }
        if(cbxmiec.isSelected()){
            int jumlah = Integer.parseInt(txtqty4.getText());
            int total;
            total=jumlah*25000;
            bayar=bayar+total;
            tampil +=cbxmiec.getText()+" Rp.25000"+ " x " +jumlah+ " = " + total+"\n";
        }
        if(cbxmied.isSelected()){
            int jumlah = Integer.parseInt(txtqty5.getText());
            int total;
            total=jumlah*23000;
            bayar=bayar+total;
            tampil +=cbxmied.getText()+" Rp.23000"+ " x " +jumlah+ " = " + total+"\n";
        }
        if(cbxmiek.isSelected()){
            int jumlah = Integer.parseInt(txtqty6.getText());
            int total;
            total=jumlah*27000;
            bayar=bayar+total;
            tampil +=cbxmiek.getText()+" Rp.27000"+ " x " +jumlah+ " = " + total+"\n";
        }
        if(cbxmies.isSelected()){
            int jumlah = Integer.parseInt(txtqty7.getText());
            int total;
            total=jumlah*30000;
            bayar=bayar+total;
            tampil +=cbxmies.getText()+" Rp.30000"+ " x " +jumlah+ " = " + total+"\n";
        }
        if(cbxkopihtm.isSelected()){
            int jumlah = Integer.parseInt(txtqty8.getText());
            int total;
            total=jumlah*6000;
            bayar=bayar+total;
            tampil +=cbxkopihtm.getText()+" Rp.6000"+ " x " +jumlah+ " = " + total+"\n";
        }
        if(cbxkopis.isSelected()){
            int jumlah = Integer.parseInt(txtqty9.getText());
            int total;
            total=jumlah*10000;
            bayar=bayar+total;
            tampil +=cbxkopis.getText()+" Rp.10000"+ " x " +jumlah+ " = " + total+"\n";
        }
        if(cbxkopisd.isSelected()){
            int jumlah = Integer.parseInt(txtqty10.getText());
            int total;
            total=jumlah*12000;
            bayar=bayar+total;
            tampil +=cbxkopisd.getText()+" Rp.12000"+ " x " +jumlah+ " = " + total+"\n";
        }
        if(cbxkopisu.isSelected()){
            int jumlah = Integer.parseInt(txtqty11.getText());
            int total;
            total=jumlah*12000;
            bayar=bayar+total;
            tampil +=cbxkopisu.getText()+" Rp.12000"+ " x " +jumlah+ " = " + total+"\n";
        }
        if(cbxkopisudi.isSelected()){
            int jumlah = Integer.parseInt(txtqty12.getText());
            int total;
            total=jumlah*14000;
            bayar=bayar+total;
            tampil +=cbxkopisudi.getText()+" Rp.14000"+ " x " +jumlah+ " = " + total+"\n";
        }
        if(cbxkopikotel.isSelected()){
            int jumlah = Integer.parseInt(txtqty13.getText());
            int total;
            total=jumlah*14000;
            bayar=bayar+total;
            tampil +=cbxkopikotel.getText()+" Rp.14000"+ " x " +jumlah+ " = " + total+"\n";
        }
        txttotal.setText(tampil +"================="+"\n"+"\n                                                                          Total Pesanan = "+bayar);
    }                                        

    private void txtqty4ActionPerformed(java.awt.event.ActionEvent evt) {                                        
        // TODO add your handling code here:
    }                                       

    private void btnresetActionPerformed(java.awt.event.ActionEvent evt) {                                         
        txtqty1.setText("");
        txtqty2.setText("");
        txtqty3.setText("");
        txtqty4.setText("");
        txtqty5.setText("");
        txtqty6.setText("");
        txtqty7.setText("");
        txtqty8.setText("");
        txtqty9.setText("");
        txtqty10.setText("");
        txtqty11.setText("");
        txtqty12.setText("");
        txtqty13.setText("");
        txttotal.setText("");
    }                                        

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MenuCafe.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MenuCafe.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MenuCafe.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MenuCafe.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MenuCafe().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify                     
    private javax.swing.JButton btnpesan;
    private javax.swing.JButton btnreset;
    private javax.swing.JCheckBox cbxkopihtm;
    private javax.swing.JCheckBox cbxkopikotel;
    private javax.swing.JCheckBox cbxkopis;
    private javax.swing.JCheckBox cbxkopisd;
    private javax.swing.JCheckBox cbxkopisu;
    private javax.swing.JCheckBox cbxkopisudi;
    private javax.swing.JCheckBox cbxmieb;
    private javax.swing.JCheckBox cbxmiec;
    private javax.swing.JCheckBox cbxmied;
    private javax.swing.JCheckBox cbxmiek;
    private javax.swing.JCheckBox cbxmies;
    private javax.swing.JCheckBox cbxmiet;
    private javax.swing.JCheckBox cbxmieu;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField txtqty1;
    private javax.swing.JTextField txtqty10;
    private javax.swing.JTextField txtqty11;
    private javax.swing.JTextField txtqty12;
    private javax.swing.JTextField txtqty13;
    private javax.swing.JTextField txtqty2;
    private javax.swing.JTextField txtqty3;
    private javax.swing.JTextField txtqty4;
    private javax.swing.JTextField txtqty5;
    private javax.swing.JTextField txtqty6;
    private javax.swing.JTextField txtqty7;
    private javax.swing.JTextField txtqty8;
    private javax.swing.JTextField txtqty9;
    private javax.swing.JTextArea txttotal;
    // End of variables declaration                   
}
